//This part of the file has been auto-generated by zeroinit.py
//obj_battleyou:
resetignoreall = 0;
hp = 0;
flasks = 0;
ignoreall = 0;
superregen = 0;
walkdir = 0;
attackcyc = 0;
damaged = 0;
image_single = 0;
img = 0;
maxspd = 0;
accel = 0;
brake = 0;
attackcycmax = 0;
mybox = 0;
regencycmax = 0;
i = 0;
joy = 0;
joyhold = 0;
imaxx = 0;
regencyc = 0;
pressleft = 0;
pressright = 0;
ignoreallprev = 0;
pressup = 0;
pressdown = 0;
pressupprev = 0;
pressdownprev = 0;
pressrightprev = 0;
pressleftprev = 0;
tempid = 0;
pressinteract = 0;
pressinteractprev = 0;
ready = 0;
active = 0;
firecyc = 0;
stopfire = 0;
z = 0;
pressubprev = array_create(50, 0);
pressub = array_create(50, 0);
pressrunprev = 0;
pressrun = 0;
joyrun = 0;
pressescapeprev = 0;
pressescape = 0;


//Below are the original contents of the file.
script_execute(scr_battleyoucreate,0,0,0,0,0);
