function __init_global() {
	gml_pragma( "global", "__init_global();");

	// set any global defaults
	layer_force_draw_depth(true,0);		// force all layers to draw at depth 0
	draw_set_colour( c_black );


}


// Mobile settings
#macro MOBILE_SETTINGS_FILE "options_mobile.sav"
#macro MOBILE_SETTINGS_VERSION 1
global.mobile_button_height = 0.8;
global.mobile_button_scale = 1;
global.mobile_lock = 0;

// Mobile inputs, not auto-generated
#macro MOBILE_DEVICE_COUNT 10
global.is_mobile = (os_type == os_android or os_type == os_ios);
global.mobile_up = false;
global.mobile_down = false;
global.mobile_left = false;
global.mobile_right = false;
global.mobile_interact = false;
global.mobile_run = false;


//This part of the file has been auto-generated by zeroinit.py
//Globals:
global.__jstick_povangle = 0;
global.flashr = 0;
global.sound = 0;
global.gmv = 0;
global.flashg = 0;
global.hearts = 0;
global.camefrom = 0;
global.difficulty = 0;
global.battle = 0;
global.playmusic = 0;
global.frames = 0;
global.maxframes = 0;
global.skipframe = 0;
global.shakescreen = 0;
global.npccured = 0;
global.battlenpc = 0;
global.npcjustcured = array_create(100, 0);
global.animcyc = 0;
global.animcyclength = 0;
global.flashspeed = 0;
global.flashb = 0;
global.bgcolor = 0;
global.flasks = 0;
global.regen = 0;
global.multi = 0;
global.force = 0;
global.pf = 0;
global.finalbossdead = 0;
global.marrytag = 0;
global.firstintro = 0;
global.marryname = 0;
global.joystickexists = 0;
global.joyup = 0;
global.joydown = 0;
global.joyleft = 0;
global.joyright = 0;
global.fliprun = 0;
global.haspov = 0;
global.savefilename = 0;
global.fromsavefile = 0;
global.destination = 0;
global.maymarry = 0;
global.playerposx = 0;
global.playerposy = 0;
global.playerdir = 0;
global.item = 0;
global.chestopened = array_create(256, 0);
global.roadblock = 0;
global.door = 0;
global.hyperchest = 0;
global.alwaysrun = 0;
global.fullscreen = 0;
global.overridefullscreen = 0;
global.windowed = 0;
global.autosave = 0;
global.pauseselected = 0;
global.world = 0;
global.roomgoto = 0;
global.init = 0;
global.boxhp = 0;
global.overridedir = 0;
global.overridedirout = 0;
global.exitedbattle = 0;
global.lastworld = 0;
global.titleinit = 0;
global.__jstick_pad1 = 0;
global.__jstick_pad2 = 0;
