//This part of the file has been auto-generated by zeroinit.py
//obj_bossenemy:
init = 0;
hp = 0;
active = 0;
type = 0;
tempid = 0;
myx = 0;
myy = 0;
stopfire = 0;
firecyc = 0;
firecyc2 = 0;
firefromx = 0;
firefromy = 0;
i = 0;
firecyc3 = 0;
firecyc4 = 0;
firecyc5 = 0;
firecyc6 = 0;
img = 0;
damaged = 0;
image_single = 0;
