//This part of the file has been auto-generated by zeroinit.py
//obj_enemyshot:
spiralcyc = 0;
image_single = 0;
ttl = 0;
imgcyc = 0;
img = 0;
phase = 0;
homing = 0;
spiral = 0;
outside = 0;
homecyc = 0;
tempid = 0;


//Below are the original contents of the file.
speed=2;
spiralcyc=1;
