//This part of the file has been auto-generated by zeroinit.py
//obj_interstar:
type = 0;
image_single = 0;
imgcyc = 0;
img = 0;


//Below are the original contents of the file.
vspeed=-4;
type=floor(random(2));

