//This part of the file has been auto-generated by zeroinit.py
//obj_deadboss:
image_single = 0;
final = 0;
cyc = 0;
myx = 0;
myy = 0;
i = 0;
tempid = 0;


//Below are the original contents of the file.
image_single=2;

