//This part of the file has been auto-generated by zeroinit.py
//obj_npc:
image_single = 0;
init = 0;
cured = 0;
img = 0;
yay = 0;
tag = 0;
name = 0;
texts = 0;
text = 0;
aftertexts = 0;
aftertext = 0;
battle = 0;
battletag = 0;
