//This part of the file has been auto-generated by zeroinit.py
//obj_flask:
zgrav = 0;
zspeed = 0;
z = 0;
image_single = 0;
i = 0;
tempid = 0;
imgcyc = 0;
img = 0;
trailcyc = 0;
trail = 0;


//Below are the original contents of the file.
zgrav=-0.4;
zspeed=4;
speed=4;

