//This part of the file has been auto-generated by zeroinit.py
//obj_intersabot:
i = 0;
joy = 0;
joyhold = 0;
imaxx = 0;
drawinit = 0;
y2 = 0;
cyc = 0;
yspd = 0;
fileid = 0;
pressescape = 0;
pressescapeprev = 0;
pressinteractprev = 0;
pressinteract = 0;
pressubprev = 0;
pressub = 0;
pressrunprev = 0;
pressrun = 0;
joyrun = 0;
pressupprev = 0;
pressup = 0;
pressdownprev = 0;
pressdown = 0;
pressleftprev = 0;
pressleft = 0;
pressrightprev = 0;
pressright = 0;


//Below are the original contents of the file.
script_execute(scr_intersabotcreate,0,0,0,0,0);
