//This part of the file has been auto-generated by zeroinit.py
//obj_titlesabot:
i = 0;
foundoptions = 0;
filefound = 0;
selected = 0;
fileid = 0;
temp = 0;
joy = 0;
joyhold = 0;
imaxx = 0;
state = 0;
tier = 0;
tiertext = 0;
j = 0;
assign = 0;
filestring = 0;
unlockreally = 0;
transition = 0;
transitioncyc = 0;
transitioncyc2 = 0;
pfx = 0;
pfy = 0;
pftext = 0;
pfsize = 0;
pffont = 0;
pflen = 0;
pfx2 = 0;
pfy2 = 0;
pfchar = 0;
pfi = 0;
str = 0;
locstr = 0;
pressescape = 0;
pressescapeprev = 0;
prevselected = 0;
loadgame = 0;
pressright = 0;
really = 0;
pressdown = 0;
pressdownprev = 0;
pressup = 0;
pressupprev = 0;
pressinteract = 0;
pressinteractprev = 0;
readyforassign = 0;
pressleft = 0;
pressleftprev = 0;
pressrightprev = 0;
tempcheckjoy = 0;
cyc = 0;
pressubprev = 0;
pressub = 0;
pressrunprev = 0;
pressrun = 0;
joyrun = 0;
tempfilename = 0;
finddifficulty = 0;
findhearts = 0;
tempbutton = 0;


//Below are the original contents of the file.
scr_createtext();
scr_titlesabotcreate();

