//This part of the file has been auto-generated by zeroinit.py
//obj_enemy:
invisible = 0;
img = 0;
image_single = 0;
damaged = 0;
type = 0;
i = 0;
init = 0;
hp = 0;
fire = 0;
ready = 0;
cyc = 0;
pdir = 0;
dir = 0;
go = 0;
subcyc = 0;
tempid = 0;
stutter = 0;
hpprev = 0;
firealt = 0;
